[package]
name = "feel"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono.workspace = true
iso8601.workspace = true
lazy_static.workspace = true
regex.workspace = true
serde.workspace = true
bigdecimal = "0.4.3"
rand = "0.8.5"
defer = "0.2.1"
